### PR TITLE
chore: Upgrade Gradle to 7.4.1

### PR DESCRIPTION
**Pull request by kingthorin**
https://services.gradle.org/distributions/gradle-7.4.1-all.zip.sha256

`./gradlew wrapper --gradle-version 7.4.1 --distribution-type all
--gradle-distribution-sha256-sum=a9a7b7baba105f6557c9dcf9c3c6e8f7e57e6b49889c5f1d133f015d0727e4be`

`./gradlew assemble --scan --warning-mode all`

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
@thc202 could I get a second opinion on this?
(I'm pretty sure it's right/fine but better safe/sure :grinning:)

**Comment by thc202** [comment]
I'd expect the wrapper JAR to change, could you run a second time?

**Comment by kingthorin** [comment]
Tks, will do.

**Comment by kingthorin** [comment]
There we go, that should be more as expected?

**Comment by thc202** [comment]
Yeah, looks good.

**Comment by kingthorin** [comment]
Thank you!

**Comment by thc202** [comment]
No problem.

**Pull request merged**
