### PR TITLE
Help formatting tweak

### PR DESCRIPTION
**Pull request by kingthorin**
https://github.com/kingthorin/neonmarker/pull/23 follow-up.

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by thc202** [comment]
You could add https://github.com/zaproxy/zap-extensions/blob/318e4f61ee9b8db67e5ec14a04135a34a9099651/addOns/reports/reports.gradle.kts#L64-L74 to automatically check/format/indent it.

**Comment by kingthorin** [comment]
Thanks I’ll do that.

**Comment by kingthorin** [comment]
@thc202 seem right/good?

**Comment by thc202** [comment]
It does.

**Comment by kingthorin** [comment]
Thanks

**Pull request merged**
