### PR TITLE
chore: Upgrade Gradle to 8.5

### PR DESCRIPTION
**Pull request by kingthorin**
`./gradlew assemble --scan --warning-mode all`

` ./gradlew wrapper --gradle-version 8.5 --distribution-type all --gradle-distribution-sha256-sum=c16d517b50dd28b3f5838f0e844b7520b8f1eb610f2f29de7e4e04a1b7c9c79b`

Per build scan
```
neonmarker
assemble
Dec 8 2023 10:15:56 EST
This build did not contain any deprecations.
```

### CODE REVIEW

**Comment by kingthorin** [comment]
@thc202 look right?

**Comment by kingthorin** [comment]
@thc202 I should have asked. Should I be changing any of the spotless setup/handling or using features from https://github.com/zaproxy/gradle-plugin-add-on ?

**Comment by thc202** [comment]
They can be definitely updated to get the latest changes but it will not save many configs, in this case only this line can be removed after the updates: https://github.com/kingthorin/neonmarker/blob/d131d7fcbaa6d632365f0402af6281c5507a6cac/build.gradle.kts#L53

**Comment by kingthorin** [comment]
Okay I'll leave it as-is for now. Thanks!

**Pull request merged**
