### PR TITLE
chore: Build and Dependency Updates

### PR DESCRIPTION
**Pull request by kingthorin**
Follow-up to zaproxy/zaproxy#6888

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
@thc202 look okay to you?

**Comment by kingthorin** [comment]
Assuming good, ZAP PRs were approved and merged.

**Comment by thc202** [comment]
For the record it looks ok, was just checking it :)

**Comment by kingthorin** [comment]
Oh thank you. I just assumed it was the weekend and you didn’t need anything extra. Once I saw the others done I figured it was good to go.

Thanks very much!!

**Pull request merged**
